// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/Pranc1ngPegasus/lambda-chi/internal/adapter/configuration"
	"github.com/Pranc1ngPegasus/lambda-chi/internal/adapter/controller/router"
	"github.com/Pranc1ngPegasus/lambda-chi/internal/adapter/lambda/handler"
)

// Injectors from injector.go:

func initialize() handler.Healthcheck {
	config := configuration.Get()
	httpHandler := router.NewRouter()
	healthcheck := handler.NewHealthcheck(config, httpHandler)
	return healthcheck
}
