// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/Pranc1ngPegasus/lambda-chi/internal/adapter/configuration"
	"github.com/Pranc1ngPegasus/lambda-chi/internal/adapter/controller/router"
	"github.com/Pranc1ngPegasus/lambda-chi/internal/adapter/controller/server"
	"net/http"
)

// Injectors from injector.go:

func initialize() *http.Server {
	handler := router.NewRouter()
	config := configuration.Get()
	httpServer := server.NewServer(handler, config)
	return httpServer
}
